FROM ubuntu:focal
RUN mkdir -p /opt/hostedtoolcache

ENV AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
ARG GH_RUNNER_VERSION="2.305.0"
ARG TARGETPLATFORM="linux"
ARG TARGET_ARCH="x64"
ARG DUMB_INIT_VERSION="1.2.2"
ARG GIT_CORE_PPA_KEY="A1715D88E1DF1F24"
ENV GIT_LFS_VERSION="3.2.0"
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
RUN apt-get -y update
RUN apt-get install -y gnupg
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${GIT_CORE_PPA_KEY}
RUN apt-get -y update && apt-get -y upgrade

RUN groupadd -g 121 runner &&  \
    useradd -mr -d /home/runner -u 1001 -g 121 runner && \
    usermod -aG sudo runner &&  \
    usermod -aG docker runner &&  \
    echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
