labels:
  - name: resolved
    labeled:
      issue:
        body: |
          This issue has been **LOCKED** because of it being resolved!

          The issue has been fixed and is therefore considered resolved.
          If you still encounter this or it has changed, open a new issue instead of responding to solved ones.
        action: close
        locking: lock
        lock_reason: resolved
  - name: inactive
    labeled:
      issue:
        body: |
          This issue has been marked as inactive.

          If you still encounter this or it has changed, add a comment to provide further information.
  - name: stale
    labeled:
      issue:
        body: |
          This issue has been **LOCKED** because of it being old.
          If you still encounter this or it has changed, open a new issue.
        action: close
        locking: lock
        lock_reason: resolved
  - name: duplicate
    labeled:
      issue:
        body: |
          This issue has been closed because of duplication.
        action: close
        locking: lock
        lock_reason: resolved
